# Generated by Django 5.0.2 on 2024-02-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsmain', '0004_teacher_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='date_joined',
            field=models.DateField(blank=True, null=True),
        ),
    ]
