# Generated by Django 5.0.2 on 2024-02-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsmain', '0005_alter_teacher_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_code', models.CharField(max_length=20)),
                ('program_name', models.CharField(max_length=50)),
                ('subjects', models.ManyToManyField(blank=True, null=True, to='cmsmain.subject')),
            ],
        ),
    ]
