# Generated by Django 5.0.2 on 2024-03-01 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsmain', '0010_alter_assignment_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='CourseClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=20)),
                ('class_name', models.CharField(max_length=30)),
                ('students', models.ManyToManyField(blank=True, related_name='classes', to='cmsmain.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsmain.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsmain.teacher')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsmain.term')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='course_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='cmsmain.courseclass'),
        ),
        migrations.AddField(
            model_name='exam',
            name='course_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='cmsmain.courseclass'),
        ),
        migrations.AddField(
            model_name='test',
            name='course_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='cmsmain.courseclass'),
        ),
    ]
