# Generated by Django 5.0.2 on 2024-03-07 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsmain', '0011_student_created_at_teacher_created_at_courseclass_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(choices=[('NA', 'Not Assigned'), ('B1', 'Building_1'), ('B2', 'Building_2'), ('B3', 'Building_3'), ('B4', 'Building_4'), ('B5', 'Building_5')], default='NA', max_length=5)),
                ('room', models.CharField(choices=[('NA', 'Not Assigned'), ('LR1', 'Lecture_Room_1'), ('LR2', 'Lecture_Room_2'), ('LR3', 'Lecture_Room_3'), ('LR4', 'Lecture_Room_4'), ('LR5', 'Lecture_Room_5'), ('CF', 'Cafeteria'), ('GM', 'Gymnasium'), ('SP', 'Swimming_Pool'), ('LB', 'Library')], default='NA', max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsmain.location'),
        ),
        migrations.AddField(
            model_name='exam',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsmain.location'),
        ),
        migrations.AddField(
            model_name='test',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsmain.location'),
        ),
    ]
