# Generated by Django 5.0.2 on 2024-03-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsmain', '0012_location_assignment_location_exam_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='building',
            field=models.CharField(choices=[('Not_Assigned', 'Not Assigned'), ('Building_1', 'Building_1'), ('Building_2', 'Building_2'), ('Building_3', 'Building_3'), ('Building_4', 'Building_4'), ('Building_5', 'Building_5')], default='Not_Assigned', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='room',
            field=models.CharField(choices=[('Not_Assigned', 'Not Assigned'), ('Lecture_Room_1', 'Lecture_Room_1'), ('Lecture_Room_2', 'Lecture_Room_2'), ('Lecture_Room_3', 'Lecture_Room_3'), ('Lecture_Room_4', 'Lecture_Room_4'), ('Lecture_Room_5', 'Lecture_Room_5'), ('Cafeteria', 'Cafeteria'), ('Gymnasium', 'Gymnasium'), ('Swimming_Pool', 'Swimming_Pool'), ('Library', 'Library')], default='Not_Assigned', max_length=20),
        ),
    ]
