# Generated by Django 5.0.2 on 2024-03-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsmain', '0014_alter_location_building_alter_location_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='location_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='building',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='room',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
