# Generated by Django 5.0.2 on 2024-03-08 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsmain', '0016_assignmark_remark_exammark_remark_testmark_remark_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='term',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='term',
        ),
        migrations.RemoveField(
            model_name='test',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='test',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='test',
            name='term',
        ),
    ]
