# Generated by Django 5.0.2 on 2024-03-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsmain', '0017_remove_assignment_subject_remove_assignment_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmark',
            name='student',
        ),
        migrations.RemoveField(
            model_name='exammark',
            name='student',
        ),
        migrations.RemoveField(
            model_name='testmark',
            name='student',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
