# Generated by Django 5.0.2 on 2024-03-08 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsmain', '0018_remove_assignmark_student_remove_exammark_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmark',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsmain.student'),
        ),
        migrations.AddField(
            model_name='exammark',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsmain.student'),
        ),
        migrations.AddField(
            model_name='testmark',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsmain.student'),
        ),
    ]
