# Generated by Django 5.0.2 on 2024-03-10 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsmain', '0019_assignmark_student_exammark_student_testmark_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseclass',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='cmsmain.subject'),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='cmsmain.teacher'),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='cmsmain.term'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='cmsmain.location'),
        ),
        migrations.AlterField(
            model_name='exammark',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exammarks', to='cmsmain.exam'),
        ),
        migrations.AlterField(
            model_name='exammark',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exammarks', to='cmsmain.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(related_name='students', to='cmsmain.subject'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(related_name='teachers', to='cmsmain.subject'),
        ),
    ]
