# Generated by Django 5.0.2 on 2024-03-11 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsmain', '0020_alter_courseclass_subject_alter_courseclass_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exammark',
            name='student',
        ),
        migrations.AlterField(
            model_name='assignmark',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignmarks', to='cmsmain.student'),
        ),
        migrations.AlterField(
            model_name='testmark',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testmarks', to='cmsmain.student'),
        ),
        migrations.AlterField(
            model_name='testmark',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testmarks', to='cmsmain.test'),
        ),
    ]
