# Generated by Django 5.0.2 on 2024-03-11 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsmain', '0022_exammark_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmark',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignmarks', to='cmsmain.student'),
        ),
        migrations.AlterField(
            model_name='exammark',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exammarks', to='cmsmain.student'),
        ),
        migrations.AlterField(
            model_name='testmark',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testmarks', to='cmsmain.student'),
        ),
        migrations.AddConstraint(
            model_name='assignmark',
            constraint=models.UniqueConstraint(fields=('student', 'assignment'), name='unique_student_assignment'),
        ),
        migrations.AddConstraint(
            model_name='exammark',
            constraint=models.UniqueConstraint(fields=('student', 'exam'), name='unique_student_exam'),
        ),
        migrations.AddConstraint(
            model_name='testmark',
            constraint=models.UniqueConstraint(fields=('student', 'test'), name='unique_student_test'),
        ),
    ]
