# Generated by Django 5.0.2 on 2024-03-13 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsmain', '0023_alter_assignmark_student_alter_exammark_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammark',
            name='exam',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exammarks', to='cmsmain.exam'),
        ),
    ]
