# Generated by Django 5.0.2 on 2024-04-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsmain', '0026_alter_assignmark_assignment_alter_exammark_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
