# Generated by Django 5.0.2 on 2024-04-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsmain', '0030_alter_exammark_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='total',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='weight',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
