# Generated by Django 5.0.2 on 2024-04-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsmain', '0031_alter_exam_total_alter_exam_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammark',
            name='mark',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
