# Generated by Django 5.0.2 on 2024-06-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsmain', '0032_alter_exammark_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
